### ISSUE TITLE
Optional config values set to `null` should be allowed

### ISSUE THREAD

**Issue by SaschaMann** [exercism/configlet#192]
Currently configlet fails if a `.meta/config.json` file contains `"forked_from": null` ([example build](https://github.com/exercism/julia/pull/331/checks?check_run_id=1946343463)).

The `.meta/config.json` files is largely generated on the Julia track, and allowing `"forked_from": null` simplifies the tooling.

The same should apply to other **optional** config values.

**Comment by SaschaMann** [comment]
Nice, thanks! :)

**Comment by ErikSchierboom** [comment]
Sure! Sorry for the wait :)

**Comment by ee7** [comment]
@SaschaMann the new configlet release `4.0.0-alpha.7` made at least [this diff](https://github.com/exercism/configlet/pull/199#pullrequestreview-616624540) to the `configlet lint` output to Julia.

But heads-up: some of the remaining errors look the same, but are due to some `forked_from` being a bare string, not an array:

```
Not an array: 'forked_from':
./exercises/concept/annalyns-infiltration/.meta/config.json

Not an array: 'forked_from':
./exercises/concept/annalyns-infiltration2/.meta/config.json

Not an array: 'forked_from':
./exercises/concept/elyses-enchantments/.meta/config.json

Not an array: 'forked_from':
./exercises/concept/lasagna/.meta/config.json

Not an array: 'forked_from':
./exercises/concept/leap/.meta/config.json

Not an array: 'forked_from':
./exercises/concept/vehicle-purchase/.meta/config.json
```

See e.g. the [concept/lasagna/.meta/config.json](
https://github.com/exercism/julia/blob/10f4d7a97c38023a3369bb2c2a74c93336ec4918/exercises/concept/lasagna/.meta/config.json#L22)
