### ISSUE TITLE
lint: check that concept exercise has correct `concepts` array

### ISSUE THREAD

**Issue by taiyab** [exercism/configlet#386]
https://exercism.lol/tracks/rust/exercises/csv-builder

![image](https://user-images.githubusercontent.com/5337876/124306428-4bcbfa80-db5e-11eb-96cc-7d73456574a4.png)

This learning exercise doesn't teach any concepts. Need to deal with edge cases like this.

**Comment by ee7** [comment]
> does configlet catch this

Not yet.

> (or is planned to catch it)?

Yeah. From https://github.com/exercism/configlet/issues/249:

> ### Rule: `config.json` file is valid
>
> The `config.json` file should have the following checks:
> - [ ] ...
> - [ ] The `"exercises.concept[].concepts"` value must be a non-empty array of strings if `"exercises.concept[].status"` is not equal to `deprecated`
> - [ ] ...
> - [ ] The `"concepts"` value must have a entry with a matching `"slug"` property for each concept listed in a concept exercise's `"concepts"` property

It looks like this issue is actually due to the latter item. From [the relevant lines in Rust's `config.json`](https://github.com/exercism/rust/blob/da8f29550083ba9df4a191ee79674abf262e6be8/config.json#L154-L167):

```json
      {
        "slug": "csv-builder",
        "name": "CSV builder",
        "difficulty": 1,
        "uuid": "10c9f505-9aef-479f-b689-cb7959572482",
        "concepts": [
          "string-vs-str"
        ],
```

We see that the exercise's `concepts` array is non-empty, but no item in the top-level `concepts` array has a `slug` with the value `string-vs-str`.

A bunch of these edge cases aren't checked yet. Sorry. I've been in `configlet sync`-land for a while.

**Comment by iHiD** [comment]
Thanks for the info!
