### ISSUE TITLE
sync: Add integration tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/configlet#4]
I'd prefer them to be integration tests, as in the tests should preferrably run the actual application

**Comment by ee7** [comment]
Let's say that this issue is closed by https://github.com/exercism/configlet/pull/176.

We currently have this test:
https://github.com/exercism/configlet/blob/b3ee3779b71ef842c4a8bd7b52da2b36c0dc04e7/tests/test_binary.nim#L35-L280

Of course, we'll want to add more tests as `sync` is overhauled, but we can track that elsewhere.
