### ISSUE TITLE
No Mac build in release 4.0.0-alpha.33

### ISSUE THREAD

**Issue by glennj** [exercism/configlet#439]
The fetch-configlet script exited non-zero. 

`curl --silent --show-error --fail --location --retry 3 --header 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/exercism/configlet/releases/latest` does not have an entry for Mac

**Comment by ee7** [comment]
See:
- https://github.com/exercism/configlet/issues/223
- https://github.com/exercism/configlet/issues/222
- https://github.com/exercism/github-actions/issues/19

TL;DR: the release is currently created when the first asset is uploaded (usually the Linux one), but the macOS build takes a long time to start. So there's a ~5 minute window after each release where the `fetch-configlet` script fails for macOS (and something like 1 minute for Windows)

Sorry for the inconvenience: this will be fixed in the future - we'll set the release as a draft until every  asset is uploaded. And the macOS build should get faster eventually. 

This time it was:
```
Wed, 13 Oct 2021 11:00:13 UTC
Creating release
https://github.com/exercism/configlet/releases/tag/4.0.0-alpha.33

Wed, 13 Oct 2021 11:00:58 UTC
Creating archive: artifacts/configlet-windows-64bit.zip

Wed, 13 Oct 2021 11:05:19 UTC
Creating archive: artifacts/configlet-mac-64bit.zip
```

**Comment by glennj** [comment]
Thanks for the info.
