### ISSUE TITLE
sync: crashes on TOML files but lint shows no problems

### ISSUE THREAD

**Issue by verdammelt** [exercism/configlet#613]
Encountered this using configlet version `4.0.0-beta.4`
I run the command `configlet sync --tests --docs --metadata --filepaths` and it crashes with the following sort of error:

```
Checking exercises...
parsetoml.nim(908)       parseValue
Error: unhandled exception: /Users/mark/SRC/exercism/common-lisp/exercises/practice/affine-cipher/.meta/tests.toml(6:16) unexpected character "e" [TomlError]
```

This is because my TOML file has lines like: `description = blah blah` rather than `description = "blah blah"`.

But `configlet lint` reports no problems. 

1. Perhaps sync should not *crash* in this case?
2. Perhaps lint could signal that the TOML file is invalid?

**Comment by ee7** [comment]
To others: see [an example problematic `tests.toml` file](https://github.com/exercism/common-lisp/blob/f521b1fb0f04/exercises/practice/affine-cipher/.meta/tests.toml).

The problem is indeed that the file contains an unquoted string, which is invalid TOML (see [the TOML spec](https://toml.io/en/v1.0.0#string)).

However, I agree that `configlet sync` could produce a better error message, and `configlet lint` could report that the toml file is invalid (tracked in https://github.com/exercism/configlet/issues/289).
