### ISSUE TITLE
sync: Consider `--non-interactive` and interactive mode instead of fixable errors

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/configlet#77]
See #76 and #75 

`--non-interactive` sync COULD return 0 if there is nothing to do, and non-zero if there are things to do, (so `--check`) unless `-y` or `-n` is given!

**Comment by ErikSchierboom** [comment]
Would `--non-interactive` only make sense for the `--check`? We have the `--mode <mode>` argument too which allows one to specify a default option instead of having to specify things interactively.

**Comment by SleeplessByte** [comment]
`--non-interactive` makes sense if `--mode` is given!

Use case is really automation :)

**Comment by ee7** [comment]
@SleeplessByte wrote in #75 about `--probSpecsDir`:
> And instead of erroring, asking if interactive, and only erroring if non-interactive?

My first implementation of `--probSpecsDir` just did "non-interactively pull any new commits if it is safe, and show what happened", but we ended up deciding to not to make any changes to the specified directory, at least for the first merged implementation.

I'd be okay with `canonical_data_syncer --probSpecsDir /tmp/my_ps` having some interactivity like:
```
Your problem-specifications repo /tmp/foo is x commits behind exercism/problem-specifications, pull them? [y/N]
``` 

As long we ensure that it's safe, and that it shouldn't confuse an inexperienced `git` user.

But personally, I think I always want the behaviour of either:

```
canonical_data_syncer --probSpecsDir /tmp/probspecs --offline
```

or

```
canonical_data_syncer --probSpecsDir /tmp/probspecs --update
```

That is: 
- If I'm going to wait for it to `fetch` then I want it to do the `merge` too.
- I don't want to have to type `y`.

But sadly I think we'll try to optimise for "be obvious and hard to misuse" rather than "reduce the number of keystrokes that @ee7 has to type", meaning that a plain `--probSpecsDir` shouldn't have the behaviour of `--offline` or `--update` by default. 

There are definitely some questions about how best to implement interactivity/non-interactivity. But I can't quite see how a `--non-interactive` option would fit in. Could you provide a `--help` message with a proposed design? In particular, what is the expected behaviour of:
```
`canonical_data_syncer --probSpecsDir /tmp/my_ps --non-interactive
```

when `/tmp/my_ps` is not up-to-date?

I'd also appreciate the thoughts of anybody who's reading this.

**Comment by SleeplessByte** [comment]
Great questions. I think hard to misuse is a good goal to strive for.

Regarding non interactive:

- If it's not up to date, it would then error.
   "Run with --update".
- If it's up to date, nothing would happen.
- If it ran with `--offline`, this entire check is skipped.

**Comment by ee7** [comment]
Now that we have https://github.com/exercism/configlet/issues/179#issuecomment-788842323, can we close this issue?

**Comment by ErikSchierboom** [comment]
Yes
